INSERT INTO "book" ("isbn", "book_name", "author", "introduction")
VALUES
('9780262531962', 'Introduction to Algorithms', 'Thomas H. Cormen', 'Introduction to Algorithms is a book on computer programming by Thomas H. Cormen.'),
('9780201616224', 'Design Patterns: Elements of Reusable Object-Oriented Software', 'Erich Gamma', 'Design Patterns is a modern classic in the literature of object-oriented development, offering timeless and elegant solutions to common problems in software design.'),
('9780131103627', 'Clean Code: A Handbook of Agile Software Craftsmanship', 'Robert C. Martin', 'Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees.'),
('9780321125217', 'The Pragmatic Programmer: Your Journey to Mastery', 'Andrew Hunt', 'The Pragmatic Programmer is one of those rare tech books you’ll read, re-read, and read again over the years.'),
('9780201485677', 'Refactoring: Improving the Design of Existing Code', 'Martin Fowler', 'As the application of object technology--particularly the Java programming language--has become commonplace, a new problem has emerged to confront the software development community.'),
('9780321563842', 'Code Complete: A Practical Handbook of Software Construction', 'Steve McConnell', 'Widely considered one of the best practical guides to programming, Steve McConnell’s original CODE COMPLETE has been helping developers write better software for more than a decade.'),
('9780321842688', 'Effective Java', 'Joshua Bloch', 'Effective Java™, Second Edition, brings together seventy-eight indispensable programmer’s rules of thumb: working, best-practice solutions for the programming challenges you encounter every day.'),
('9780201633610', 'Test-Driven Development: By Example', 'Kent Beck', 'Quite simply, test-driven development is meant to eliminate fear in application development. While some fear is healthy (often viewed as a conscience that tells programmers to "be careful!"), the author believes that byproducts of fear include tentative, grumpy, and uncommunicative programmers who are unable to absorb constructive criticism.'),
('9780201835953', 'Patterns of Enterprise Application Architecture', 'Martin Fowler', 'The practice of enterprise application development has benefited from the emergence of many new enabling technologies.'),
('9780201733860', 'Domain-Driven Design: Tackling Complexity in the Heart of Software', 'Eric Evans', 'Domain-Driven Design fills that need. This is not a book about specific technologies. It offers readers a systematic approach to domain-driven design, presenting an extensive set of design best practices, experience-based techniques, and fundamental principles that facilitate the development of software projects facing complex domains.') ;